#!/bin/bash

# required env variables
REQUIRED_VARIABLES="
AWS_APP_COGNITO_REGION
AWS_APP_COGNITO_APP_CLIENT_ID
AWS_APP_COGNITO_USER_POOL_ID
AWS_APP_COGNITO_IDENTITY_POOL_ID
AWS_APP_SERVICE_ENDPOINT
"

for VARIABLE in $REQUIRED_VARIABLES
do
      name="$VARIABLE"

      if [ -z "${!VARIABLE}" ]; then
        echo "==> ERROR: $VARIABLE is not set"
        exit 0
      else
        echo "==> $VARIABLE => ${!VARIABLE}"
      fi
done

export REACT_APP_AWS_APP_COGNITO_REGION=$AWS_APP_COGNITO_REGION
export REACT_APP_AWS_APP_COGNITO_APP_CLIENT_ID=$AWS_APP_COGNITO_APP_CLIENT_ID
export REACT_APP_AWS_APP_COGNITO_USER_POOL_ID=$AWS_APP_COGNITO_USER_POOL_ID
export REACT_APP_AWS_APP_COGNITO_IDENTITY_POOL_ID=$AWS_APP_COGNITO_IDENTITY_POOL_ID
export REACT_APP_AWS_APP_SERVICE_ENDPOINT=$AWS_APP_SERVICE_ENDPOINT

env | grep REACT_APP | sort
