---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Create Static Site

  Usage examples

  * First set some environment variables
  source ./app-env.sh

  * Create dev environment
  aws cloudformation create-stack --stack-name client-dev --template-body file://static-site-stack.yaml --parameters ParameterKey=AcmCertificateArn,ParameterValue=$AWS_RJS_ACMCERTIFICATEARN

  * Delete dev environment
  aws s3 rm s3://dev-app.rudijs.com --recursive
  aws cloudformation delete-stack --stack-name client-dev

Parameters:
  Environment:
    Description: The environment to use.
    Type: String
    Default: dev
    AllowedValues: ["dev", "staging", "prod"]
    ConstraintDescription: must be dev, staging or production

  DomainName:
    Type: String
    AllowedPattern: ".+"
    Default: rudijs.com

  SubDomain:
    Type: String
    AllowedPattern: ".+"
    Default: app

  AcmCertificateArn:
    Type: String
    AllowedPattern: ".+"

Conditions:
  IsProduction: !Equals [!Ref Environment, "prod"]

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - IsProduction
        - !Join [".", [!Ref SubDomain, !Ref DomainName]]
        - !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      Tags:
        - Key: "Environment"
          Value: !Ref "Environment"

  StaticSiteBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "StaticSiteBucket"
      PolicyDocument:
        Statement:
          - Action:
              - "s3:ListBucket"
            Effect: "Allow"
            Resource:
              - Fn::GetAtt: [StaticSiteBucket, Arn]
            Principal: "*"
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt: [StaticSiteBucket, Arn]
                  - "/*"
            Principal: "*"

  CloudfrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: RjsClientOriginAccessID

  StaticSiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
        Origins:
          - Id: RjsClientOriginID
            DomainName: !GetAtt [StaticSiteBucket, RegionalDomainName]
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - "/"
                  - - origin-access-identity
                    - cloudfront
                    - !Ref CloudfrontOriginAccessIdentity
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: RjsClientOriginID
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 404
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        Logging:
          Bucket: !GetAtt [CloudFrontLogsBucket, DomainName]
          Prefix: cloudfront-logs/
          IncludeCookies: false
      Tags:
        - Key: "Environment"
          Value: !Ref "Environment"

  StaticSiteDomainName:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !If
        - IsProduction
        - !Join [".", [!Ref SubDomain, !Ref DomainName]]
        - !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
      Type: A
      HostedZoneName: !Join ["", [!Ref DomainName, "."]]
      AliasTarget:
        DNSName: !GetAtt [StaticSiteCDN, DomainName]
        # CloudFront distribution Specify Z2FDTNDATAQYW2 for the HostedZoneId
        HostedZoneId: Z2FDTNDATAQYW2

  CloudFrontLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - IsProduction
        - !Join [".", [!Ref SubDomain, !Ref DomainName, "analytics"]]
        - !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName, "analytics"]]]]
      Tags:
        - Key: "Environment"
          Value: !Ref "Environment"

Outputs:
  StaticSiteBucketName:
    Value:
      Ref: StaticSiteBucket
