---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Create Static Site

  Usage examples

  * First set some environment variables
  source ./app-env.sh

  * Create dev environment
  aws cloudformation create-stack --stack-name client-dev --template-body file://static-site-stack.yaml \
  --parameters \
  ParameterKey=AcmCertificateArn,ParameterValue=$AWS_RJS_ACMCERTIFICATEARN \
  ParameterKey=HostedZoneId,ParameterValue=$AWS_RJS_HOSTEDZONEID

  * Delete dev environment
  aws cloudformation delete-stack --stack-name client-dev

Parameters:
  Environment:
    Description: The environment to use.
    Type: String
    Default: dev
    AllowedValues: ["dev", "staging", "production"]
    ConstraintDescription: must be dev, staging or production

  DomainName:
    Type: String
    AllowedPattern: ".+"
    Default: rudijs.com

  SubDomain:
    Type: String
    AllowedPattern: ".+"
    Default: app

  AcmCertificateArn:
    Type: String
    AllowedPattern: ".+"

  HostedZoneId:
    Type: String
    AllowedPattern: ".+"

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["", [!Ref Environment, "-", !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  StaticSiteBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "StaticSiteBucket"
      PolicyDocument:
        Statement:
          - Action:
              - "s3:ListBucket"
            Effect: "Allow"
            Resource:
              - Fn::GetAtt: [StaticSiteBucket, Arn]
            Principal: "*"
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt: [StaticSiteBucket, Arn]
                  - "/*"
            Principal: "*"

  CloudfrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: SSVClientOriginAccessID

  StaticSiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
        Origins:
          - Id: SSVClientOriginID
            DomainName: !GetAtt [StaticSiteBucket, RegionalDomainName]
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - "/"
                  - - origin-access-identity
                    - cloudfront
                    - !Ref CloudfrontOriginAccessIdentity
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: SSVClientOriginID
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only

  StaticSiteDomainName:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Join ["-", [!Ref Environment, !Join [".", [!Ref SubDomain, !Ref DomainName]]]]
      Type: A
      HostedZoneName: !Join ["", [!Ref DomainName, "."]]
      AliasTarget:
        DNSName: !GetAtt [StaticSiteCDN, DomainName]
        HostedZoneId: !Ref HostedZoneId

Outputs:
  StaticSiteBucketName:
    Value:
      Ref: StaticSiteBucket
