service: serverless-seed-app-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function # https://github.com/functionalone/serverless-iam-roles-per-function

custom:
  prune:
    automatic: true
    number:
  cognito:
    userPoolId: ${env:AWS_APP_COGNITO_USER_POOL_ID, 'unset-user-pool'}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    REGION: ${self:provider.region}
    USER_POOL_ID: ${self:custom.cognito.userPoolId}

functions:
  hello:
    handler: functions/get.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam

  users:
    handler: functions/users.main
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        # Resource: "arn:aws:cognito-idp:${self:provider.region}:#{AWS::AccountId}:*"
        Resource: "arn:aws:cognito-idp:${self:provider.region}:#{AWS::AccountId}:userpool/${self:custom.cognito.userPoolId}"

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
